### ISSUE TITLE
Error descriptor

### ISSUE THREAD

**Issue by aluismarte** [Artur-/KeyActions#1]
Resolve error obtaining dependencies: Failed to read artifact descriptor for org.vaadin.artur:KeyActions:jar:0.1.0 (Use --stacktrace to see the full trace)
Error |
Failed to read artifact descriptor for org.vaadin.artur:KeyActions:jar:0.1.0

IntelliJ 14 + Grails 2.4.3 + Vaadin 7.3.7

// Conf for vaadin plugin.
mavenRepo "http://maven.vaadin.com/vaadin-addons"
compile "org.vaadin.artur:KeyActions:0.1.0"

**Comment by Artur-** [comment]
There seems to be some problem with dependencies and the Maven repository. Please try 0.1.1 to see if it resolves the problem.

**Comment by aluismarte** [comment]
Fix, thanks
